events {}

http {
  server {
    listen 80;
    server_name _;

    location / {
      return 200 "Test config from homework\n";
      add_header Content-Type text/plain;
    }

    location /health {
      return 200 "OK\n";
      add_header Content-Type text/plain;
    }
  }
}
